### ISSUE TITLE
Rules API

### ISSUE THREAD

**Issue by alexconstantin** [querqy/querqy#383]
Hello,

First of all congratulation and thank you for this amazing project. We are beginning to integrate Querqy into our current project at the moment. Everything is going as expected at the moment, except the rule configuration API. The applied rules can get pretty complex, such as (taken from the docs):

```
notebook =>
  SYNONYM: laptop
  DOWN(100): case
  @{
    _id: "ID1",
    _log: "notebook,modified 2019-04-03",
    group: "electronics",
    enabled: true,
    priority: 100,
    tenant: ["t1",   "t2", "t3"],
    culture: {
      "lang": "en",
      "country": ["gb", "us"]
    }
  }@
```

If I understood correctly, this rule must be client generated and passed a parameter in a string format (with line breaks included). Is there a better way of doing this (using solrj, for example)? Am I missing something from the docs? 

Thank you!

**Comment by renekrie** [comment]
Hi @alexconstantin,

There is a bit of support using the `querqy.solr.rewriter.commonrules.CommonRulesConfigRequestBuilder`, for example:

```
   final SaveRewriterConfigSolrResponse response = new CommonRulesConfigRequestBuilder()
                    .rules("a =>\n SYNONYM: b")
                    .buildSaveRequest("rewriter_test_save")
                    .process(mySolrJClient);
``` 
(copied from QuerqyRewriterRequestHandlerSolrCloudTest). Instead of passing `rules` as a String, you could also provide an InputStream from which it would read the rule definitions.

Usually, users of Querqy maintain the rules in a tool (like SMUI) that would generate the rules file and then post it to Solr. (See, for example, push_common_rules.py in the Chorus template app: https://github.com/querqy/chorus/tree/main/smui/conf).

We don't currently support a more fine-grained rule building API. I guess it would have to be an extension of the CommonRulesConfigRequestBuilder as this is something specific to the CommonRulesRewriter. I know that @JohannesDaniel has worked on creating an object model for common rules parsing. I'm not sure if it can also be used to build rules and then generate a string config property. @JohannesDaniel ?

**Comment by mkr** [comment]
I think if you programmatically want to create rules files, you could (untested!) use code similar to the helper in [MultiLineParserTest#rule](https://github.com/querqy/querqy/blob/1dbafde2eddc0938b309bbe955f127148671fd41/querqy-core/src/test/java/querqy/rewrite/rules/rule/skeleton/MultiLineParserTest.java#L72) and serialize that using [MultiLineParserTest#asText](https://github.com/querqy/querqy/blob/1dbafde2eddc0938b309bbe955f127148671fd41/querqy-core/src/test/java/querqy/rewrite/rules/rule/skeleton/MultiLineParserTest.java#L105). What's your use case for programmatically creating rules?

**Comment by alexconstantin** [comment]
@renekrie @mkr Thank you for your answers! I think that the helper @mkr mentioned might do the trick. I'll give it a try.
